export const DISPLAY_ALERT = 'SHOW_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const LOGOUT_USER = 'LOGOUT_USER';

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const HANDLE_FILE_CHANGE = 'HANDLE_FILE_CHANGE';
export const HANDLE_QUILL_CHANGE = 'HANDLE_QUILL_CHANGE';
export const CLEAR_VALUES = 'CLEAR_VALUES';

export const CREATE_BLOG_BEGIN = 'CREATE_BLOG_BEGIN';
export const CREATE_BLOG_SUCCESS = 'CREATE_BLOG_SUCCESS';
export const CREATE_BLOG_ERROR = 'CREATE_BLOG_ERROR';

export const GET_BLOGS_BEGIN = 'GET_BLOGS_BEGIN';
export const GET_BLOGS_SUCCESS = 'GET_BLOGS_SUCCESS';

export const SET_EDIT_BLOG = 'SET_EDIT_BLOG';

export const DELETE_BLOG_BEGIN = 'DELETE_BLOG_BEGIN';

export const EDIT_BLOG_BEGIN = 'EDIT_BLOG_BEGIN';
export const EDIT_BLOG_SUCCESS = 'EDIT_BLOG_SUCCESS';
export const EDIT_BLOG_ERROR = 'EDIT_BLOG_ERROR';

export const CREATE_GALLERY_BEGIN = 'CREATE_GALLERY_BEGIN';
export const CREATE_GALLERY_SUCCESS = 'CREATE_GALLERY_SUCCESS';
export const CREATE_GALLERY_ERROR = 'CREATE_GALLERY_ERROR';
